name: Deploy Docker Image by GithubAction

on:
  push:
    branches:
      - main

jobs:
  my_job:
    name: build and deploy
    runs-on: ubuntu-latest

    steps:
      - name: get new code
        uses: actions/checkout@v2

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm

      - name: Install deps
        run: npm install

      - name: Build
        run: npm run build

      - name: Login
        run: docker login --username=${{ secrets.DOCKER_NAME }} --password=${{ secrets.DOCKER_PASSWORD }}

      - name: SSH login
        run: ssh $${{ secrets.REMOTE_NAME }}@${{ secrets.REMOTE_PASSWORD}}

      - name: ssh login
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.REMOTE_HOST }} #云服务器的ip
          username: ${{ secrets.REMOTE_USER }} #云服务器的用户名
          password: ${{ secrets.PASSWORD }} #云服务器的密码
          script: cd ~ && sh deploy.sh ${{ secrets.DOCKER_USERNAME }} ${{ secrets.DOCKER_PASSWORD }} #运行脚本

