name: Deploy to GitHub

on:
  pull_request:
    branches:
      - main

jobs:
  my_job:
    name: deploy
    runs-on: ubuntu-latest
    
    steps:
      - name: get new code
        uses: actions/checkout@v2
      
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: npm
        
      - name: build
        run: |
          npm install
          npm run build
          
      - name: FTP-Deploy-Action
        uses: SamKirkland/FTP-Deploy-Action@2.0.0
        env:
          FTP_SERVER: ${{ secrets.REMOTE_HOST }}
          FTP_USERNAME: ${{ secrets.REMOTE_USER }}
          FTP_PASSWORD: ${{ secrets.PASSWORD }}
          LOCAL_DIR: ./build/
          REMOTE_DIR: ${{ secrets.SERVER_DESTINATION }}
          METHON: sftp
          PORT: ${{ SERVER_PORT }}
